### ISSUE TITLE
Do not push new Unknown channels - stone yes record them

### ISSUE THREAD

**Issue by LoveScanner** [chuot/rdio-scanner#227]
Every time I hear new Talkgroups they are playing straight to me even I disable the group "UNKNOWN"

Lest you get me wrong - I have no problem it goes under UNKNOWN and is recorded but I do not want to hear it right now.

Is there a way to handle this settings level?

**Comment by chuot** [comment]
Well that's by design. Toggling on and off groups from the SELECT TG screen will turn off talkgroups attached to that group. However, if a new talkgroup is being discovered while the AUTO POPULATE option is activated, it will be sent anyway.

I may change the code to check the current status for the GROUP and if it is completly off, then the newly added talkgroup won't be activated, but if the group if partially activated (yellow led) or fully activated, the new talkgroup will be activated as usual.

For now, if that bugs you, just turn off the AUTO POPULATE option.

**Comment by LoveScanner** [comment]
Ok thanks i will check it out
What do you expect from the new version?
I'm sure everyone's waiting ... :)

‫בתאריך יום ב׳, 27 ביוני 2022 ב-15:52 מאת ‪Chrystian Huot‬‏ <‪
***@***.***‬‏>:‬

**Comment by chuot** [comment]
It's out already
