### ISSUE TITLE
Allow full text to be displayed on Select TG panel

### ISSUE THREAD

**Issue by theY4Kman** [chuot/rdio-scanner#33]
When I'm using rdio-scanner from my phone, the names on the Select TG panel are very often ellipsized. Because a lot of them share the same prefix, it's impossible to differentiate them:

![image](https://user-images.githubusercontent.com/33840/103204047-72199080-48c4-11eb-96aa-327356b30e6f.png)

It would be nice if a `title=` tag could be added, so a hover could reveal the full title. Though, I suppose some kind of tooltip might be necessary for mobile, where mouseover doesn't exist.

**Comment by chuot** [comment]
The ellipsis is by design and are there because I want Rdio Scanner to as good on PC and on smart devices with smaller screen. I also have performance issue with that panel when too many talkgroups are loaded in. That is why I ditched the angular-flex-layout package and why I change to mat-sidenav from pushing the screen to hovering. Having a tooltip on every buttons would make thing worst.

Since you've hilighted the group section on the select panel, I would recommend you to change those group labels with shorter prefixes (i.e. stp instead of st peters...).
