### ISSUE TITLE
Port 3000 to 80

### ISSUE THREAD

**Issue by babooino** [chuot/rdio-scanner#4]
Hello i'm running rdio-scanner and trunk-recorder on VM in local network, when trying to access it at port 3000 it works. 
I need to make it work on web so i create reverse proxy on my apache2 web server which is running on different VM in same subnet.

ProxyRequests Off
SSLProxyEngine on
 
<Proxy https://scan.webserver.xyz/>
  Order deny,allow
  Allow from all
</Proxy>

<Location />
      Order deny,allow
      Allow from all
</Location>

ProxyPass / 192.168.1.100:3000
ProxyPassReverse / 192.168.1.100:3000

Webpage loads OK, archive works fine and plays records, but live feed moitoring does not work. 
How to setup reverse proxy properly? Thank you.

**Comment by chuot** [comment]
First, make sure that the `proxy_wstunnel` module is loaded into your Apache. Since *Rdio Scanner* uses WebSockets, your Apache has to deal with it.

Depending on your Apache configuration, the following should work in a `<location>...</location>`, or in a `.htaccess` file as I do with my own configuration.

```
RewriteEngine On

###
# If you want to protect against unauthorized access.
###
#
#AuthType Basic
#AuthName "Rdio Scanner"
#AuthUserFile /[path to your htdocs]/.htpasswd
#Require expr %{HTTP:UPGRADE} =~ m#^websocket$#i
#Require expr %{REQUEST_URI} =~ m#^/.well-known/acme-challenge/|^/assets/#
#Require valid-user

###
# If you want secure connections.
# You can visit letsencrypt.org to get free SSL certificates.
###
#
#RewriteCond %{HTTPS} !=on [OR]
#RewriteCond %{HTTP_HOST} !^[your public hostname or ip address]$ [NC]
#RewriteRule ^/?(.*)$ https://[your public hostname or ip address]/$1 [L,R=301]

###
# WebSocket proxy...
###
#
RewriteCond %{HTTP:CONNECTION} ^upgrade$ [NC,OR]
RewriteCond %{HTTP:UPGRADE} ^websocket$ [NC]
RewriteRule ^/?(.*)$ ws://[internal hostname or ip address]:3000/$1 [P,L]

###
# Regular proxy, except for .well-known folder which is used
# by letsencrypt.org (certbot).
###
#
RewriteCond %{REQUEST_URI} !^/.well-known/.*$ [NC]
RewriteRule ^/?(.*)$ http://radio:3000/$1 [P,L] 
```

This setup works well for me, but you may need to tweak it a bit to fit your own configuration.

You can request more help on *gitter*, see the link in the `README.md` file.
