### ISSUE TITLE
Is there a way to remove a system once it is uploaded or to modify an existing system?

### ISSUE THREAD

**Issue by kswanson71** [chuot/rdio-scanner#9]
Absolutely awesome application!!

I was wondering if there is a way to either delete a system from the database or to overwrite a system with new data.

One thing that I have noticed in running multiple trunk-recorders into the interface is that for very large systems, ensuring arrangement of TG selection seems to be pulled, in order from the database of talkgroups imported through the "upload-systems.sh" script.

I'm importing from a local trunk-recorder instance and also one from several states away (Georgia and Ohio) into a single interface.  The number of talkgroups is a little overwhelming. :-)

Once again, awesome interface!!

**Comment by chuot** [comment]
Thank you very much for your kind words.

To modify an existing system, upload the new version of the TALKGROUP.CSV
file over the same SYSTEM_ID.

To delete a system, upload an empty file instead of TALKGROUP.CSV. For my
part I created a file with the name of EMPTY.CSV that I use for that.

Le lun. 9 déc. 2019, à 17 h 33, kswanson71 <notifications@github.com> a
écrit :

**Comment by kswanson71** [comment]
Worked perfectly!!

Thank you again for your help and such an awesome tool!

Kevin Swanson
